apiVersion: v1
kind: Pod
metadata:
  name: example
  labels:
    app: hello-openshift
    forceselinuxrelabel.admission.node.openshift.io/enabled: "true"
  namespace: test
spec:
  volumes:
    - name: task-pv-storage
      persistentVolumeClaim:
        claimName: task-pv-claim
  containers:
    - name: hello-openshift
      image: openshift/hello-openshift
      ports:
        - containerPort: 8080
      volumeMounts:
        - mountPath: "/data"
          name: task-pv-storage
      resources:
        limits:
          memory: "512Mi"
          cpu: "2000m"
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
          - ALL
  securityContext:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
