name: Build & Release Image

env:
  REGISTRY: ghcr.io
  IMAGE_REPO: ${{ github.repository }}
  IMAGE_ROOT_PATH: images
  BUILD_PLATFORM: linux/amd64,linux/arm64
  REGISTER_USER: ${{ github.actor }}
  REGISTER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}

on:
  workflow_dispatch:
  push:
    branches:
      - master
    tags:
      - v*

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Login registry
        run: |
          echo "${{ env.REGISTER_PASSWORD }}" | docker login ${{ env.REGISTRY }} -u ${{ env.REGISTER_USER }} --password-stdin

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: image=moby/buildkit:master

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_REPO }}

      - name: Build & Pushing ClusterResourceOverride
        uses: docker/build-push-action@v5.1.0
        with:
          context: .
          file: ${{ env.IMAGE_ROOT_PATH }}/distroless/Dockerfile
          labels: ${{ steps.meta.outputs.labels }}
          platforms: ${{ env.BUILD_PLATFORM }}
          tags: ${{ steps.meta.outputs.tags }}
          push: true
  